### ISSUE TITLE
short.ly

### ISSUE THREAD

**Issue by hernanex3** [lambdaclass/exercises#5]
Simple bit.ly clone. Receives long urls and returns another but shorter. Should support simple http post/get for that, and also use websocket to show in '/new' the new links shortened.

**Comment by hernanex3** [comment]
PR at https://github.com/lambdaclass/exercises/pull/8

**Comment by unbalancedparentheses** [comment]
please change names in the code to shortly

**Comment by hernanex3** [comment]
Name changed #12
